from typing import Literal

product_type_name_literals = Literal[
    "",
    "Vest top",
    "Bra",
    "Underwear Tights",
    "Socks",
    "Leggings/Tights",
    "Sweater",
    "Top",
    "Trousers",
    "Hair clip",
    "Umbrella",
    "Pyjama jumpsuit/playsuit",
    "Bodysuit",
    "Hair string",
    "Hoodie",
    "Hair/alice band",
    "Belt",
    "Boots",
    "Bikini top",
    "Swimwear bottom",
    "Underwear bottom",
    "Swimsuit",
    "Skirt",
    "T-shirt",
    "Dress",
    "Hat/beanie",
    "Kids Underwear top",
    "Shorts",
    "Shirt",
    "Cap/peaked",
    "Pyjama set",
    "Sneakers",
    "Sunglasses",
    "Cardigan",
    "Gloves",
    "Earring",
    "Bag",
    "Blazer",
    "Other shoe",
    "Jumpsuit/Playsuit",
    "Sandals",
    "Jacket",
    "Costumes",
    "Robe",
    "Scarf",
    "Coat",
    "Other accessories",
    "Polo shirt",
    "Slippers",
    "Night gown",
    "Hat/brim",
    "Tailored Waistcoat",
    "Ballerinas",
    "Tie",
    "Necklace",
    "Pyjama bottom",
    "Bracelet",
    "Blouse",
    "Outdoor overall",
    "Watch",
    "Underwear body",
    "Beanie",
    "Giftbox",
    "Sleeping sack",
    "Dungarees",
    "Outdoor trousers",
    "Wallet",
    "Swimwear set",
    "Swimwear top",
    "Flat shoe",
    "Garment Set",
    "Ring",
    "Waterbottle",
    "Wedge",
    "Long John",
    "Outdoor Waistcoat",
    "Pumps",
    "Flip flop",
    "Bootie",
    "Fine cosmetics",
    "Heeled sandals",
    "Nipple covers",
    "Hair ties",
    "Underdress",
    "Underwear set",
    "Sarong",
    "Soft Toys",
    "Earrings",
    "Heels",
    "Cap",
    "Side table",
    "Dog Wear",
]

product_group_name_literals = Literal[
    "",
    "Garment Upper body",
    "Underwear",
    "Socks & Tights",
    "Garment Lower body",
    "Accessories",
    "Items",
    "Nightwear",
    "Shoes",
    "Swimwear",
    "Garment Full body",
    "Underwear/nightwear",
    "Cosmetic",
    "Furniture",
]

color_literals = Literal[
    "",
    "Black",
    "White",
    "Beige",
    "Grey",
    "Blue",
    "Pink",
    "Lilac Purple",
    "Red",
    "Mole",
    "Orange",
    "Metal",
    "Brown",
    "Turquoise",
    "Yellow",
    "Khaki green",
    "Green",
    "undefined",
    "Unknown",
    "Yellowish Green",
    "Bluish Green",
]

index_group_name_literals = Literal[
    "",
    "Ladieswear",
    "Baby/Children",
    "Menswear",
    "Sport",
    "Divided",
]
